openapi: 3.0.2
info:
  title: API BACKEND
  version: 0.0.0
tags:
  - name: system
    description: For system use
  - name: setting
    description: For settings and management
  - name: chat
    description: For chat

paths:
  /health:
    get:
      tags:
        - system
      summary: Health check
      description: Endpoint for health checks from ALB
      responses:
        "204":
          description: OK(No Content)

components:
  schemas:
    ActionStatus:
      type: string
      description: Correspondence status
      enum:
        - EMPTY
        - REQUIRED
        - NEED_ACTION
        - COMPLETED
