name: ci-server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"

      - name: Codegen
        run: npm run codegen

      - name: Check lint
        run: |
          npm run validate

      - name: DB migration
        run: npm run docker:up  -- --wait && npm run db:migrate
        env:
          DATABASE_URL: "postgresql://shop_admin:pAssw0rd@localhost:5432/shop?schema=public"
          STAGE_NAME: local
